---
AWSTemplateFormatVersion: "2010-09-09"

Description: AWS CloudFormation Template for Skillbrowser Static

Parameters:
  BucketName:
    Type: String
    Description: The name for the bucket hosting your website

Resources:
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      WebsiteConfiguration:
        IndexDocument: index.html

  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal: "*"
            Action:
              - s3:GetObject
            Resource: !Sub "arn:aws:s3:::${WebsiteBucket}/*"

Outputs:
  WebsiteURL:
    Value: !GetAtt [WebsiteBucket, WebsiteURL]

  S3BucketSecureURL:
    Value: !Join ['', ['https://', !GetAtt [WebsiteBucket, DomainName]]]