---
AWSTemplateFormatVersion: "2010-09-09"

Description: Master AWS CloudFormation Template for Skillbrowser

Parameters:
  LambdaBucketName:
    Type: String
    Description: The name for the bucket hosting project lambda

  TemplateBucketName:
    Type: String
    Description: The name for the bucket hosting project templates

Resources:
  TemplateBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Ref TemplateBucketName

  LambdaBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Ref LambdaBucketName

Outputs:
  TemplateBucket:
   Value: !GetAtt [TemplateBucket, Arn]

  LambdaBucket:
    Value: !GetAtt [LambdaBucket, Arn]